[project]
name = "anonimizer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "environs>=14.5.0",
    "fastapi>=0.124.2",
    "pytest>=9.0.2",
    "uvicorn>=0.38.0",
]